# Generated by Django 3.2 on 2022-04-05 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='All', on_delete=django.db.models.deletion.CASCADE, to='post.category'),
        ),
    ]
