# Generated by Django 3.2 on 2022-04-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_post_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="city",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=16, max_digits=22, null=True
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=16, max_digits=22, null=True
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="postcode",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
