# Generated by Django 3.2 on 2022-04-19 14:23

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="image",
        ),
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=16, max_digits=22, null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=16, max_digits=22, null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True, default="profile_pics/default.jpg", upload_to="profile_pics"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="postcode",
            field=models.CharField(
                default="", max_length=8, validators=[user.models.validate_postcode]
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="street",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="street_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
