# Generated by Django 3.2 on 2022-04-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_auto_20220419_1334"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="postcode",
            field=models.CharField(default="", max_length=8),
            preserve_default=False,
        ),
    ]
