# Generated by Django 3.2 on 2022-04-19 14:00

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_auto_20220419_1335"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True, default="profile_pics/default.jpg", upload_to="profile_pics"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="postcode",
            field=models.CharField(
                max_length=8, validators=[user.models.validate_postcode]
            ),
        ),
    ]
