# Generated by Django 3.2 on 2022-04-19 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_auto_20220419_1400"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="image",
            new_name="photo",
        ),
    ]
